import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import "./globals.css";

import type { Metadata } from "next";
import { Header } from "@/components/Header";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider
          theme={{
            primaryColor: "orange",
          }}
        >
          <Header />
          <main>{children}</main>
        </MantineProvider>
      </body>
    </html>
  );
}
